### ISSUE TITLE
我如何知道一个构造器里全部的东西是干嘛的？比如这里的div

### ISSUE THREAD

**Issue by YueMeiHong** [kiochan/moko-forum#3]
https://github.com/kiochan/moko-forum/blob/4d9d07f0d200d2ed2456ae884a69066c0a6abd18/components/view/Container.tsx#L3

styled应该是Next Ui上自带的，div以后的参数也都能看懂，但是div是哪里来的？只能看Next Ui中的style教学部分吗？VScode鼠标悬停可以看到div以后的，但是我看不到div，该是什么其他操作吗？

**Comment by kiochan** [comment]
通常上来讲，你可以看这个函数（而非构造器）来自于哪个库，这通常可以在`import`语句中看到，例如：
https://github.com/kiochan/moko-forum/blob/4d9d07f0d200d2ed2456ae884a69066c0a6abd18/components/view/Container.tsx#L1

在这里你可以看到 `styled` 引用自 `next-ui` 。

那么你就可以通过Google，寻找这个库，这样你会找到他的官网。
https://nextui.org/

通常在里面搜索你想要查找的函数就可以找到对应的文档：
![image](https://github.com/kiochan/moko-forum/assets/12151173/5801a0d3-50a7-4551-b31c-4adbc576ada7)

以下是 `styled` 对应的文档链接：
https://nextui.org/docs/theme/override-styles#using-the-styled-function

希望可以帮助到你。

**Comment by YueMeiHong** [comment]
我在这个网页搜索了一下div，发现
![图片](https://github.com/kiochan/moko-forum/assets/86508535/2c7d8236-74ae-4b9c-b585-a2b497018603)
div是html的元素？一部分？我看了一些例子，但是我还是不理解，我对这个概念有一些猜测，也看了一些示例
![图片](https://github.com/kiochan/moko-forum/assets/86508535/0b090d50-6a81-4f5b-bc0d-41432698ff9c)
但是还是没太理解，因为我没学过html也没用过html。这个div到底是干嘛的？我注意到在这里Container ，为啥不直接不用div，直接用Container完成呢？

**Comment by kiochan** [comment]
DIV相关文档在这里：
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/div

div 用于划分出一块独立的区域，方便组织代码。

在这里我们将带有特定样式的 div，作为了 `Contianer` 组件。用于组织代码。

你可以将 `Contianer` 视为：

```jsx
<div style={{
    boxSizing: "border-box",
    height: "100vh",
    display: 'flex',
    flexDirection: 'column',
}}></div>
```

**Comment by kiochan** [comment]
如果没有更多问题 我先关闭这个issue
