### ISSUE TITLE
进入话题之，将左上角的Logo改编为返回按钮

### ISSUE THREAD

**Issue by kiochan** [kiochan/moko-forum#4]
![image](https://github.com/kiochan/moko-forum/assets/12151173/9ce614c1-7dd0-451c-9f10-f3fc753ec9e3)

在此处添加一个返回按钮，替换原本的Logo。
这样的话用户可以比较清楚如何返回。

**Comment by kiochan** [comment]
请记得新开一个branch @YueMeiHong

**Comment by YueMeiHong** [comment]
@kiochan 我尝试了大概2小时左右，一点头绪都没有
1.尝试了Navbar文件直接删logo部分加了按钮，结果主界面也没有logo只有返回了
![图片](https://github.com/kiochan/moko-forum/assets/86508535/061a4972-fda1-4a35-8944-80c9fecd191a)

2.尝试了自己创建一个控制Navbar状态的文件叫NavbarContext，但是网上找的示例文件用到了children我完全不理解
![图片](https://github.com/kiochan/moko-forum/assets/86508535/098c2393-0be8-40df-829f-01509eb097e8)

3.看了眼代码发现layout里也有用到Navbar跟children，好像Navbar的状态是在这里控制的？加了一行专门用来控制左上角状态的代码`leftRightConer: React.ReactNode`，但是感觉哪里不太对，后面也没啥头绪了。

今天寄了！

**Comment by kiochan** [comment]
你可以尝试在 `Navbar` 中添加一个 `props` 取名为 `returnButtonName?: string`
并且以此来控制是否显示按钮

当 returnButtonName 有值的时候，则显示为按钮。
没有数值的时候则显示 <Logo /> 组件。

同时，为了更好地控制，你也可以添加一个 `returnTo:? string` 用于控制返回的位置。 

我认为你并不需要 `components/widget/NavbarContext.tsx` 这个文件

**Comment by YueMeiHong** [comment]
1. 在/component/widet/Navbar里做的更改 interface NavbarProps这里添加了returnButtonName跟returnTo

![图片](https://github.com/kiochan/moko-forum/assets/86508535/d251dce9-7f4d-4b19-b051-ca944961025c)

2. 跟同样Navbar里的 Navbarfunction Navbar中NextUINavBar里添加了判断returnButtonName的部分

![图片](https://github.com/kiochan/moko-forum/assets/86508535/56efbb92-712b-4aaf-8e3a-2f3f622b846e)



问题是我根本不知道returnButtonName在哪里被赋值了，所以继续了如下更改

3.  在/component/view/Layout里做的更改LayoutProps这里添加了returnButtonName跟returnTo
     Layout里添加了returnButtonName跟returnTo

![图片](https://github.com/kiochan/moko-forum/assets/86508535/1505fe73-b66f-405e-8557-f7240f260a9a)



但是都没有解决问题，寄！

@kiochan
